# Generated by Django 3.2.8 on 2021-12-14 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newuser',
            options={'verbose_name': 'user'},
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='is_staff',
        ),
        migrations.AlterModelTable(
            name='newuser',
            table=None,
        ),
    ]
