# Generated by Django 3.2.9 on 2021-12-08 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='newuser',
            old_name='First_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='newuser',
            old_name='Last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='newuser',
            old_name='Phone_number',
            new_name='phone_number',
        ),
    ]
