# Generated by Django 4.1 on 2023-10-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0010_rename_puser_completedtopics_user'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='completed_topics',
            field=models.ManyToManyField(blank=True, to='sms.topics'),
        ),
    ]
