# Generated by Django 3.2.9 on 2021-12-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='username',
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
