# Generated by Django 3.2.9 on 2021-12-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='phone_number',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
