# Generated by Django 4.1.7 on 2023-06-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="status_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Premium", "PREMIUM"),
                    ("Free", "FREE"),
                    ("Sponsored", "SPONSORED"),
                ],
                default="premium",
                max_length=225,
                null=True,
            ),
        ),
    ]
