# Generated by Django 4.1 on 2023-12-02 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referrer',
            old_name='name',
            new_name='names',
        ),
    ]
