# Generated by Django 4.1 on 2023-12-02 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='newuser',
            table=None,
        ),
    ]
