# Generated by Django 4.1 on 2023-12-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referrer',
            name='learner',
        ),
        migrations.AddField(
            model_name='referrer',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
