# Generated by Django 4.1 on 2023-12-03 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='newuser',
            table='auth_user',
        ),
    ]
