# Generated by Django 4.1 on 2023-12-02 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_name_referrer_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referrer',
            name='referred_students',
        ),
        migrations.RemoveField(
            model_name='referrer',
            name='referrer',
        ),
    ]
