# Generated by Django 4.1.7 on 2023-06-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile_status_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="status_type",
            field=models.CharField(
                choices=[
                    ("Premium", "PREMIUM"),
                    ("Free", "FREE"),
                    ("Sponsored", "SPONSORED"),
                ],
                default="Free",
                max_length=225,
            ),
        ),
    ]
