# Generated by Django 3.2.9 on 2021-12-08 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_country_profile_countries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='country',
            new_name='countries',
        ),
    ]
