# Generated by Django 4.1 on 2023-10-29 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0013_remove_courses_student_course'),
        ('users', '0002_profile_completed_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='student_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='sms.courses'),
        ),
    ]
