# Generated by Django 4.1 on 2023-12-03 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_newuser_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='code',
        ),
    ]
