# Generated by Django 3.2.9 on 2022-07-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_cert_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cert_img',
            field=models.ImageField(blank=True, default='newlogo3.jpg', null=True, upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pro_img',
            field=models.ImageField(blank=True, default='newlogo3.jpg', null=True, upload_to='profile'),
        ),
    ]
