# Generated by Django 3.2.9 on 2022-07-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220720_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cert_img',
            field=models.ImageField(blank=True, default='profile/newlogo3.jpg', null=True, upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pro_img',
            field=models.ImageField(blank=True, default='profile/newlogo3.jpg', null=True, upload_to='profile'),
        ),
    ]
