# Generated by Django 3.2.9 on 2021-12-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='countries',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
