# Generated by Django 4.1.7 on 2023-06-05 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0013_remove_blog_author_remove_courses_student"),
        ("users", "0003_alter_profile_status_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="courses",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="sms.courses",
            ),
        ),
    ]
