# Generated by Django 4.1 on 2023-12-02 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_referrer_referred_students_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Referrer',
        ),
    ]
