# Generated by Django 4.1 on 2024-01-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_newuser_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='student_class',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
