# Generated by Django 3.2.9 on 2021-12-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_newuser_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='country',
            field=models.CharField(blank=True, choices=[('Nigeria', 'Nigeria'), ('United State', 'United State'), ('Nigeria', 'Nigeria')], max_length=254, null=True),
        ),
    ]
