# Generated by Django 4.1 on 2023-12-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_newuser_is_staff_alter_newuser_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='referral_code',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
