# Generated by Django 4.1 on 2023-12-12 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_newuser_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='phone_number',
            new_name='referral_code',
        ),
    ]
