# Generated by Django 4.1 on 2023-12-13 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_newuser_referral_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='referral_code',
        ),
    ]
