# Generated by Django 4.1 on 2023-12-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_referrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='referral_code',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
