# Generated by Django 3.1.4 on 2022-08-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220728_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cert_img',
        ),
        migrations.AlterField(
            model_name='profile',
            name='pro_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
