# Generated by Django 5.0.4 on 2025-08-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_first_name_alter_profile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
