# Generated by Django 4.1 on 2023-12-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_newuser_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrerprofile',
            name='referred_students',
            field=models.ManyToManyField(blank=True, related_name='referrer_profiles', to='users.profile'),
        ),
    ]
