# Generated by Django 5.0.4 on 2025-08-20 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_alter_topics_slug'),
        ('users', '0007_newuser_last_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.courses')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'verbose_name': 'Badge Download',
                'verbose_name_plural': 'Badge Downloads',
            },
        ),
    ]
