# Generated by Django 5.0.4 on 2025-08-20 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0041_course_categories'),
        ('users', '0008_badgedownload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgedownload',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.course'),
        ),
    ]
