# Generated by Django 5.0.4 on 2026-03-14 11:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_badgedownload_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('visit_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('entry_page', models.URLField(blank=True, max_length=500)),
                ('referrer', models.URLField(blank=True, max_length=500)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('os', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('page_views', models.IntegerField(default=1)),
                ('session_ended', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visit_time'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('time_on_page', models.IntegerField(default=0)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='users.uservisit')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='uservisit',
            index=models.Index(fields=['user', '-visit_time'], name='users_userv_user_id_2bb36d_idx'),
        ),
        migrations.AddIndex(
            model_name='uservisit',
            index=models.Index(fields=['-visit_time'], name='users_userv_visit_t_9d960e_idx'),
        ),
        migrations.AddIndex(
            model_name='uservisit',
            index=models.Index(fields=['session_key'], name='users_userv_session_532347_idx'),
        ),
    ]
