# Generated by Django 4.1 on 2023-12-01 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_referrerprofile_referrer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referrerprofile',
            name='referred_students',
            field=models.ManyToManyField(blank=True, related_name='referrer_profiles', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='referrerprofile',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_users', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='referrerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
