# Generated by Django 4.1 on 2023-12-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_referrerprofile_referred_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='referral_code',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='referral_code',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='referrerprofile',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
