# Generated by Django 4.1 on 2023-12-02 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_newuser_referral_code_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='newuser',
            table=None,
        ),
    ]
