# Generated by Django 4.1 on 2023-12-02 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_newuser_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='referral_code',
        ),
        migrations.AlterModelTable(
            name='newuser',
            table='auth_user',
        ),
    ]
