# Generated by Django 4.1 on 2023-12-02 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_referrer_delete_referrerprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referrer',
            old_name='user',
            new_name='learner',
        ),
    ]
