# Generated by Django 4.1 on 2023-12-02 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_rename_user_referrer_learner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referrer',
            name='learner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
