# Generated by Django 3.2.9 on 2022-07-05 16:22

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields
import hitcount.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=225, null=True, unique=True)),
                ('img_source', models.CharField(max_length=225, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('img_blog', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('desc', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=225, null=True, unique=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='fff', max_length=225, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, default='fff', max_length=225, null=True)),
                ('last_name', models.CharField(blank=True, max_length=225, null=True)),
                ('title', models.CharField(blank=True, max_length=225, null=True)),
                ('desc', models.TextField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=225)),
                ('desc', models.TextField(default='')),
                ('course_link', models.URLField(blank=True, max_length=225, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=225, null=True, unique=True)),
                ('objectives', models.TextField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('student_activity', models.TextField(blank=True, null=True)),
                ('evaluation', models.TextField(blank=True, null=True)),
                ('img_topic', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('img_tutorial', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('topics_url', models.CharField(blank=True, choices=[('https://t.me/joinchat/4F9VVjDPLzAwM2Q0', 'Beginners python_url'), ('https://t.me/joinchat/5CBRm0mlq5VlZmE0', 'Beginners html_url'), ('https://t.me/joinchat/8qkzp31B9EE1YjY0', 'Beginners statistic_url'), ('https://t.me/joinchat/xRjZ9vXkUx43NmY0', 'Beginners django_url'), ('https://t.me/joinchat/hgBXeiRmfDA1M2M0', 'Beginners sql_url'), ('https://t.me/joinchat/NF7h8BKK_vFjOTk8', 'Beginners javascripts_url')], max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.categories')),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.courses')),
            ],
        ),
    ]
