# Generated by Django 3.2.8 on 2021-11-29 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoriess',
            new_name='Categories',
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Coursess',
            new_name='Courses',
        ),
        migrations.RenameModel(
            old_name='Topicss',
            new_name='Topics',
        ),
    ]
