# Generated by Django 3.2.9 on 2021-12-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topics',
            old_name='descs',
            new_name='desc',
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(blank=True, default='fff', max_length=225, null=True, unique=True),
        ),
    ]
