# Generated by Django 3.2.8 on 2021-11-21 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Categoriess',
        ),
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comments',
        ),
        migrations.RenameModel(
            old_name='Courses',
            new_name='Coursess',
        ),
        migrations.RenameModel(
            old_name='Topics',
            new_name='Topicss',
        ),
    ]
