# Generated by Django 4.1.7 on 2023-04-14 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="courses", name="img_partdesc1",),
        migrations.RemoveField(model_name="courses", name="img_partdesc2",),
        migrations.RemoveField(model_name="courses", name="partdesc1",),
        migrations.RemoveField(model_name="courses", name="partdesc2",),
        migrations.RemoveField(model_name="courses", name="partdesc3",),
    ]
