# Generated by Django 4.1 on 2023-07-25 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sms", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="courses",
            name="student",
            field=models.ManyToManyField(
                blank=True, related_name="courses", to="users.profile"
            ),
        ),
        migrations.AddField(
            model_name="courselearnerreviews",
            name="courses",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="sms.courses"
            ),
        ),
        migrations.AddField(
            model_name="coursefrequentlyaskquestions",
            name="courses",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="sms.courses"
            ),
        ),
        migrations.AddField(
            model_name="careeropportunities",
            name="courses",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="sms.courses"
            ),
        ),
        migrations.AddField(
            model_name="blogcomment",
            name="post",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comments",
                to="sms.blog",
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.profile",
            ),
        ),
        migrations.AddField(
            model_name="aboutcourseowner",
            name="courses",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="sms.courses"
            ),
        ),
    ]
