# Generated by Django 4.1.7 on 2023-04-14 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="courses", old_name="partdesc11", new_name="partdesc1",
        ),
    ]
