# Generated by Django 4.1 on 2023-07-25 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="profilestudent", name="user",),
        migrations.DeleteModel(name="CourseEnrolled",),
        migrations.DeleteModel(name="ProfileStudent",),
    ]
