# Generated by Django 4.1 on 2023-07-28 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="courselearnerreviews",
            old_name="courses",
            new_name="courses_review",
        ),
    ]
