# Generated by Django 4.1 on 2023-07-25 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="courses", name="student",),
    ]
