# Generated by Django 4.1 on 2024-02-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_remove_course_schools'),
        ('sms', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='schools',
            field=models.ManyToManyField(blank=True, related_name='courses', to='quiz.school'),
        ),
    ]
