# Generated by Django 4.1 on 2023-07-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courses",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                default="500",
                max_digits=10,
                max_length=225,
                null=True,
            ),
        ),
    ]
