# Generated by Django 4.1.7 on 2023-05-14 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0002_remove_courses_img_partdesc1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courses",
            name="categories",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="sms.categories",
            ),
        ),
    ]
