# Generated by Django 5.0.4 on 2025-08-14 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_courses_schools'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topics',
            options={'ordering': ['title']},
        ),
    ]
