# Generated by Django 3.2.8 on 2022-01-15 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_course_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_links',
            name='topics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.topics'),
        ),
    ]
