# Generated by Django 4.1 on 2022-12-30 20:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0003_topics_coursedesc"),
    ]

    operations = [
        migrations.AddField(
            model_name="categories",
            name="img_course",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
