# Generated by Django 4.1.7 on 2023-04-14 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0003_courses_img_img_partdesc2_courses_img_partdesc1"),
    ]

    operations = [
        migrations.RenameField(
            model_name="courses",
            old_name="img_img_partdesc2",
            new_name="img_partdesc2",
        ),
    ]
