# Generated by Django 4.1 on 2023-07-28 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0003_alter_courselearnerreviews_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courselearnerreviews",
            name="courses",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courselearner",
                to="sms.courses",
            ),
        ),
        migrations.AlterField(
            model_name="courselearnerreviews",
            name="desc",
            field=models.TextField(null=True),
        ),
    ]
