# Generated by Django 4.1.7 on 2023-06-02 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("sms", "0003_alter_alert_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="courses",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.profile",
            ),
        ),
    ]
