# Generated by Django 3.2.9 on 2022-07-22 17:40

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='desc',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
