# Generated by Django 4.1 on 2023-08-03 17:40

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0003_alter_courses_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topics",
            name="desc",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
