# Generated by Django 4.1 on 2023-07-28 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0003_rename_courses_courselearnerreviews_courses_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courselearnerreviews",
            name="courses_review",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courselearner",
                to="sms.courses",
            ),
        ),
        migrations.AlterField(
            model_name="courselearnerreviews",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
