# Generated by Django 3.2.9 on 2022-07-22 17:42

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_alter_blog_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='desc',
            field=tinymce.models.HTMLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='desc',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AlterField(
            model_name='topics',
            name='desc',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
