# Generated by Django 4.1.7 on 2023-05-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0004_courses_course_logo_courses_course_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="courses",
            name="status_type",
            field=models.CharField(
                blank=True,
                choices=[("premium", "PREMIUM"), ("free", "FREE")],
                default="premium",
                max_length=225,
                null=True,
            ),
        ),
    ]
