# Generated by Django 4.1.7 on 2023-04-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0004_rename_img_img_partdesc2_courses_img_partdesc2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courses",
            name="partdesc1",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
