# Generated by Django 4.1 on 2023-08-03 18:20

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0004_alter_topics_desc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topics", name="desc", field=tinymce.models.HTMLField(null=True),
        ),
    ]
