# Generated by Django 4.1 on 2023-07-28 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0004_alter_courselearnerreviews_courses_review_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="CourseLearnerReviews",),
    ]
