# Generated by Django 4.1 on 2022-12-30 20:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0004_categories_img_course"),
    ]

    operations = [
        migrations.RemoveField(model_name="categories", name="img_course",),
        migrations.AddField(
            model_name="courses",
            name="img_course",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
