# Generated by Django 4.1.7 on 2023-06-04 18:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0005_frequentlyaskquestions"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="img_ebook",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="Ebook images"
            ),
        ),
    ]
