# Generated by Django 4.1.7 on 2023-05-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0005_courses_status_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courses",
            name="course_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Course", "COURSE"),
                    ("Professional Certificate", "PROFESSIONAL CERTIFICATE"),
                    ("Specialization", "SPECIALIZATION"),
                    ("Degree", "DEGREE"),
                    ("Diploma", "DIPLOMA"),
                ],
                default="Course",
                max_length=225,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="courses",
            name="status_type",
            field=models.CharField(
                blank=True,
                choices=[("Premium", "PREMIUM"), ("Free", "FREE")],
                default="Premium",
                max_length=225,
                null=True,
            ),
        ),
    ]
