# Generated by Django 3.2.9 on 2022-01-21 10:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_courses_course_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='img_topic',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
