# Generated by Django 5.0.4 on 2025-08-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_alter_topics_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatyouwillbuild',
            name='desc',
            field=models.TextField(blank=True, max_length=900, null=True),
        ),
    ]
