# Generated by Django 3.2.9 on 2022-07-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_auto_20220722_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
