# Generated by Django 4.1 on 2023-08-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0005_alter_topics_desc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skillyouwillgain",
            name="title",
            field=models.TextField(blank=True, max_length=900, null=True),
        ),
    ]
