# Generated by Django 4.1 on 2022-12-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0005_remove_categories_img_course_courses_img_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topics", name="slug", field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name="topics",
            name="title",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
