# Generated by Django 5.0.4 on 2025-08-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0006_alter_whatyouwillbuild_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='is_programming',
            field=models.BooleanField(default=False),
        ),
    ]
