# Generated by Django 4.1 on 2023-01-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0006_alter_topics_slug_alter_topics_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, null=True)),
                ("content", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
