# Generated by Django 3.2.9 on 2022-01-21 12:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0006_alter_topics_img_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='img_tutorial',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
