# Generated by Django 4.1.7 on 2023-05-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0006_alter_courses_course_type_alter_courses_status_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courses",
            name="course_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("course", "COURSE"),
                    ("Professional Certificate", "PROFESSIONAL CERTIFICATE"),
                    ("Specialization", "SPECIALIZATION"),
                    ("Degree", "DEGREE"),
                    ("Diploma", "DIPLOMA"),
                ],
                default="course",
                max_length=225,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="courses",
            name="status_type",
            field=models.CharField(
                blank=True,
                choices=[("premium", "PREMIUM"), ("free", "FREE")],
                default="premium",
                max_length=225,
                null=True,
            ),
        ),
    ]
