# Generated by Django 4.1 on 2023-10-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0006_alter_skillyouwillgain_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
