# Generated by Django 3.1.4 on 2022-08-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0007_auto_20220728_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='poster',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
