# Generated by Django 4.1 on 2023-10-08 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('sms', '0007_topics_is_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.topics')),
            ],
        ),
    ]
