# Generated by Django 4.1.7 on 2023-06-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0007_alter_alert_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
