# Generated by Django 4.1.7 on 2023-03-10 10:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0007_alert"),
    ]

    operations = [
        migrations.AddField(
            model_name="categories",
            name="img_cat",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="cat"
            ),
        ),
    ]
