# Generated by Django 5.0.4 on 2026-02-09 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0007_courses_is_programming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.categories'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='courses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.courses'),
        ),
    ]
