# Generated by Django 4.1 on 2023-10-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('sms', '0008_completedtopics'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='completed_by',
            field=models.ManyToManyField(through='sms.CompletedTopics', to='users.profile'),
        ),
    ]
