# Generated by Django 3.1.4 on 2022-08-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0008_blog_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
