# Generated by Django 5.0.4 on 2026-02-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0008_alter_topics_categories_alter_topics_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='video',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
