# Generated by Django 3.2.9 on 2022-01-29 13:29

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0008_auto_20220126_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
