# Generated by Django 5.0.4 on 2026-02-20 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0009_alter_topics_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topics',
            options={'ordering': ['created']},
        ),
    ]
