# Generated by Django 4.1.7 on 2023-05-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0009_alter_courses_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courses",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default="20000",
                max_digits=10,
                max_length=225,
                null=True,
            ),
        ),
    ]
