# Generated by Django 4.1.7 on 2023-06-04 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0009_partners"),
    ]

    operations = [
        migrations.RenameField(
            model_name="partners", old_name="img_ebook", new_name="img_partner",
        ),
    ]
