# Generated by Django 4.1.7 on 2023-03-10 21:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0009_alter_categories_img_cat"),
    ]

    operations = [
        migrations.AddField(
            model_name="topics",
            name="desc_home",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
