# Generated by Django 3.1.4 on 2022-08-02 00:02

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0009_topics_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='objectives',
            field=tinymce.models.HTMLField(default='gghj'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
