# Generated by Django 5.0.4 on 2026-02-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0010_alter_topics_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topics',
            options={'ordering': ['created'], 'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
        migrations.AddField(
            model_name='topics',
            name='expected_output',
            field=models.TextField(blank=True, help_text='Expected output or requirements for code validation (AI will check intelligently)', null=True),
        ),
        migrations.AddField(
            model_name='topics',
            name='quiz_correct_answer',
            field=models.TextField(blank=True, help_text='The correct answer (AI will accept variations)', null=True),
        ),
        migrations.AddField(
            model_name='topics',
            name='quiz_options',
            field=models.JSONField(blank=True, default=list, help_text='Optional: Multiple choice options as JSON array ["Option A", "Option B", "Option C"]'),
        ),
        migrations.AddField(
            model_name='topics',
            name='quiz_question',
            field=models.TextField(blank=True, help_text='Quiz question for non-programming topics', null=True),
        ),
        migrations.AddField(
            model_name='topics',
            name='validation_hints',
            field=models.TextField(blank=True, help_text='Hints to show students if they struggle (optional)', null=True),
        ),
        migrations.AddField(
            model_name='topics',
            name='validation_type',
            field=models.CharField(choices=[('code', 'Code Output Validation'), ('quiz', 'Quiz Question'), ('manual', 'Manual Completion')], default='manual', help_text='How should this topic be validated?', max_length=20),
        ),
    ]
