# Generated by Django 4.1.7 on 2023-05-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0010_alter_courses_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courses",
            name="course_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Course", "COURSE"),
                    ("Professional Certificate", "PROFESSIONAL CERTIFICATE"),
                    ("Specialization", "SPECIALIZATION"),
                    ("Degree", "DEGREE"),
                    ("Diploma", "DIPLOMA"),
                ],
                default="course",
                max_length=225,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="courses",
            name="status_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Premium", "PREMIUM"),
                    ("Free", "FREE"),
                    ("Sponsored", "SPONSORED"),
                ],
                default="premium",
                max_length=225,
                null=True,
            ),
        ),
    ]
