# Generated by Django 4.1 on 2023-10-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0010_rename_puser_completedtopics_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='cert_price',
            field=models.DecimalField(blank=True, decimal_places=0, default='1000', max_digits=10, max_length=225, null=True),
        ),
    ]
