# Generated by Django 3.1.4 on 2022-08-02 00:03

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0010_auto_20220802_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='objectives',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
