# Generated by Django 4.1.7 on 2023-06-05 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0011_alter_courses_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courses",
            name="categories",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="categories",
                to="sms.categories",
            ),
        ),
    ]
