# Generated by Django 5.0.4 on 2026-02-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0011_alter_topics_options_topics_expected_output_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='validation_type',
            field=models.CharField(choices=[('code', 'Code Output Validation'), ('quiz', 'Quiz Question'), ('manual', 'Manual Completion')], default='code', help_text='How should this topic be validated?', max_length=20),
        ),
    ]
