# Generated by Django 4.1.7 on 2023-03-12 14:19

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0011_remove_topics_desc_home_courses_desc_home"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoursesDesc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("desc", tinymce.models.HTMLField(default="")),
            ],
        ),
    ]
