# Generated by Django 4.1 on 2023-10-29 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0011_courses_cert_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='student_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='sms.courses'),
        ),
    ]
