# Generated by Django 4.1.7 on 2023-06-05 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0012_alter_courses_categories"),
    ]

    operations = [
        migrations.RemoveField(model_name="blog", name="author",),
        migrations.RemoveField(model_name="courses", name="student",),
    ]
