# Generated by Django 4.1.7 on 2023-03-12 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0012_coursesdesc"),
    ]

    operations = [
        migrations.DeleteModel(name="CoursesDesc",),
    ]
