# Generated by Django 5.0.4 on 2026-02-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0012_alter_topics_validation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='test_cases',
            field=models.JSONField(default=list, help_text='Test cases: [{"input": "5", "expected_output": "25"}]'),
        ),
    ]
