# Generated by Django 4.1.7 on 2023-03-15 17:19

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0013_delete_coursesdesc"),
    ]

    operations = [
        migrations.AddField(
            model_name="courses",
            name="desc_heading",
            field=tinymce.models.HTMLField(default=""),
        ),
    ]
