# Generated by Django 5.0.4 on 2026-06-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0041_course_categories'),
        ('sms', '0013_topics_test_cases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='desc',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=225, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='desc',
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=225, null=True),
        ),
        migrations.AddIndex(
            model_name='categories',
            index=models.Index(fields=['name'], name='sms_categor_name_119fa9_idx'),
        ),
        migrations.AddIndex(
            model_name='categories',
            index=models.Index(fields=['name', 'desc'], name='sms_categor_name_bf21c7_idx'),
        ),
        migrations.AddIndex(
            model_name='courses',
            index=models.Index(fields=['title'], name='sms_courses_title_95ff99_idx'),
        ),
        migrations.AddIndex(
            model_name='courses',
            index=models.Index(fields=['desc'], name='sms_courses_desc_607015_idx'),
        ),
        migrations.AddIndex(
            model_name='courses',
            index=models.Index(fields=['title', 'desc'], name='sms_courses_title_7e89b3_idx'),
        ),
    ]
