# Generated by Django 3.1.4 on 2022-08-02 20:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220728_0045'),
        ('sms', '0013_auto_20220802_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcomment',
            options={},
        ),
        migrations.RenameField(
            model_name='blogcomment',
            old_name='body',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='active',
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='post',
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images'),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
