# Generated by Django 4.1.7 on 2023-03-16 09:24

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0014_courses_desc_heading"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courses",
            name="course_desc",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="courses",
            name="desc_heading",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="courses",
            name="title",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
