# Generated by Django 4.1.7 on 2023-06-05 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_profile_courses"),
        ("sms", "0014_blog_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="courses",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.profile",
            ),
        ),
    ]
