# Generated by Django 3.1.4 on 2022-08-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0015_auto_20220802_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='date_posted',
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
