# Generated by Django 4.1.7 on 2023-03-17 10:51

import cloudinary.models
from django.db import migrations, models
import hitcount.models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0015_alter_courses_course_desc_alter_courses_desc_heading_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhotoGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=225, null=True, unique=True
                    ),
                ),
                ("desc", models.TextField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "img_cat",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="image"
                    ),
                ),
            ],
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
    ]
