# Generated by Django 4.1.7 on 2023-06-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0015_courses_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courses",
            name="status_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Premium", "PREMIUM"),
                    ("Free", "FREE"),
                    ("Sponsored", "SPONSORED"),
                ],
                default="Free",
                max_length=225,
                null=True,
            ),
        ),
    ]
