# Generated by Django 4.1.7 on 2023-03-17 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0016_photogallery"),
    ]

    operations = [
        migrations.RemoveField(model_name="photogallery", name="desc",),
    ]
