# Generated by Django 4.1.7 on 2023-06-08 10:58

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0016_alter_courses_status_type"),
    ]

    operations = [
        migrations.RemoveField(model_name="courses", name="course_link",),
        migrations.AddField(
            model_name="courses",
            name="faqs",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="courses",
            name="skillyouwillgain",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name="courses",
            name="whatyouwilllearn",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
