# Generated by Django 3.1.4 on 2022-08-02 22:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0016_auto_20220802_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='img_blogcomment',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
