# Generated by Django 3.1.4 on 2022-08-02 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0017_auto_20220802_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='title',
        ),
    ]
