# Generated by Django 4.1.7 on 2023-03-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0017_remove_photogallery_desc"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, null=True)),
                ("content", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(name="PhotoGallery",),
    ]
