# Generated by Django 4.1.7 on 2023-06-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0018_alter_courses_faqs"),
    ]

    operations = [
        migrations.AddField(
            model_name="frequentlyaskquestions",
            name="course_type",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
