# Generated by Django 3.1.4 on 2022-08-03 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0018_remove_blogcomment_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='comment',
            new_name='post',
        ),
    ]
