# Generated by Django 4.1.7 on 2023-03-17 11:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0018_gallery_delete_photogallery"),
    ]

    operations = [
        migrations.RemoveField(model_name="gallery", name="content",),
        migrations.RemoveField(model_name="gallery", name="created",),
        migrations.AddField(
            model_name="gallery",
            name="gallery",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
