# Generated by Django 3.1.4 on 2022-08-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0019_auto_20220803_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
