# Generated by Django 4.1.7 on 2023-06-09 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0019_frequentlyaskquestions_course_type"),
    ]

    operations = [
        migrations.RemoveField(model_name="courses", name="faqs",),
    ]
