# Generated by Django 3.1.4 on 2022-08-04 15:47

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0020_auto_20220804_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='objectives',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topics',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='topics',
            name='student_activity',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
