# Generated by Django 4.1.7 on 2023-04-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0020_remove_courses_desc_heading_remove_topics_evaluation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topics", name="slug", field=models.SlugField(max_length=500),
        ),
    ]
