# Generated by Django 3.1.4 on 2022-08-04 22:52

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0021_auto_20220804_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
