# Generated by Django 4.1.7 on 2023-06-09 10:06

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0022_remove_coursefaqs_course_type_remove_courses_faqs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursefaqs",
            name="course_type",
            field=tinymce.models.HTMLField(blank=True, max_length=500, null=True),
        ),
    ]
