# Generated by Django 3.1.4 on 2022-08-05 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0023_auto_20220804_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='author',
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
