# Generated by Django 4.1.7 on 2023-06-09 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0024_remove_coursefaqs_course_type"),
    ]

    operations = [
        migrations.RemoveField(model_name="coursefaqs", name="courses",),
        migrations.AddField(
            model_name="coursefaqs",
            name="faqs_courses",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="sms.courses"
            ),
        ),
    ]
