# Generated by Django 4.1.7 on 2023-06-09 10:23

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0025_remove_coursefaqs_courses_coursefaqs_faqs_courses"),
    ]

    operations = [
        migrations.RemoveField(model_name="coursefaqs", name="faqs_courses",),
        migrations.AddField(
            model_name="coursefaqs",
            name="course_type",
            field=tinymce.models.HTMLField(blank=True, max_length=500, null=True),
        ),
    ]
