# Generated by Django 4.1 on 2022-08-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0025_alter_blog_id_alter_blogcomment_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topics", name="slug", field=models.SlugField(),
        ),
    ]
