# Generated by Django 4.1 on 2022-08-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0027_alter_topics_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topics",
            name="topics_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
