# Generated by Django 4.1 on 2022-08-29 12:51

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0028_alter_topics_topics_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="courses",
            name="course_desc",
            field=tinymce.models.HTMLField(default=""),
        ),
    ]
