# Generated by Django 4.1.7 on 2023-06-09 11:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0028_remove_topics_img_tutorial_alter_topics_img_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="img_blog",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="blog image"
            ),
        ),
        migrations.AlterField(
            model_name="blogcomment",
            name="img_blogcomment",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="comment image"
            ),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="gallery",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="gallery image"
            ),
        ),
    ]
