# Generated by Django 4.1.7 on 2023-06-10 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0029_alter_blog_img_blog_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="courses", name="skillyouwillgain",),
        migrations.CreateModel(
            name="Skillyouwillgain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=225, null=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "courses",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sms.courses",
                    ),
                ),
            ],
        ),
    ]
