# Generated by Django 4.1.7 on 2023-06-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0030_remove_courses_skillyouwillgain_skillyouwillgain"),
    ]

    operations = [
        migrations.RemoveField(model_name="courses", name="whatyouwilllearn",),
        migrations.AlterField(
            model_name="courses",
            name="desc",
            field=models.TextField(blank=True, null=True),
        ),
    ]
