# Generated by Django 4.1.7 on 2023-06-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0031_remove_courses_whatyouwilllearn_alter_courses_desc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topics",
            name="desc",
            field=models.TextField(blank=True, null=True),
        ),
    ]
