# Generated by Django 4.1.7 on 2023-06-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0032_alter_topics_desc"),
    ]

    operations = [
        migrations.RemoveField(model_name="courses", name="course_desc",),
        migrations.RemoveField(model_name="courses", name="desc_home",),
        migrations.AlterField(
            model_name="courses", name="desc", field=models.TextField(null=True),
        ),
    ]
