# Generated by Django 4.1.7 on 2023-06-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0035_alter_courses_course_desc_alter_courses_desc_home"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courses",
            name="course_desc",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="courses",
            name="desc_home",
            field=models.TextField(blank=True, null=True),
        ),
    ]
