# Generated by Django 4.1.7 on 2023-06-14 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_profile_courses"),
        ("sms", "0038_whatyouwilllearn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courselearnerreviews",
            name="desc",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="courses",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="users.profile",
            ),
        ),
    ]
