# Generated by Django 4.1.7 on 2023-06-14 13:27

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0040_careeropportunities"),
    ]

    operations = [
        migrations.RemoveField(model_name="careeropportunities", name="title",),
        migrations.AlterField(
            model_name="careeropportunities",
            name="desc",
            field=tinymce.models.HTMLField(blank=True, max_length=500, null=True),
        ),
    ]
