# Generated by Django 4.1.7 on 2023-06-15 11:18

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0041_remove_careeropportunities_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="careeropportunities",
            name="desc",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coursefaqs",
            name="title",
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name="skillyouwillgain",
            name="title",
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name="whatyouwilllearn",
            name="desc",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
