# Generated by Django 4.1.7 on 2023-06-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0042_alter_careeropportunities_desc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whatyouwilllearn",
            name="desc",
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
