# Generated by Django 4.1.7 on 2023-06-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0045_alter_frequentlyaskquestions_desc"),
    ]

    operations = [
        migrations.RemoveField(model_name="coursefaqs", name="faqs_courses",),
        migrations.RemoveField(model_name="coursefaqs", name="updated",),
        migrations.AddField(
            model_name="coursefaqs",
            name="course_type",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="coursefaqs",
            name="desc",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coursefaqs",
            name="title",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
