# Generated by Django 4.1.7 on 2023-06-15 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0046_remove_coursefaqs_faqs_courses_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Coursefaqs", new_name="CourseFrequentlyAskQuestions",
        ),
    ]
