# Generated by Django 4.1.7 on 2023-06-15 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0047_rename_coursefaqs_coursefrequentlyaskquestions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursefrequentlyaskquestions", name="course_type",
        ),
        migrations.AddField(
            model_name="coursefrequentlyaskquestions",
            name="courses",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="sms.courses"
            ),
        ),
    ]
