# Generated by Django 4.1.7 on 2023-06-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0048_remove_coursefrequentlyaskquestions_course_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topics", name="slug", field=models.SlugField(unique=True),
        ),
    ]
