# Generated by Django 4.1.7 on 2023-06-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0051_remove_courseprerequisites_courses_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="courses", name="prerequisite",),
        migrations.AddField(
            model_name="courses",
            name="prerequisites",
            field=models.ManyToManyField(blank=True, to="sms.courses"),
        ),
    ]
