# Generated by Django 4.1.7 on 2023-06-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0052_remove_courses_prerequisite_courses_prerequisites"),
    ]

    operations = [
        migrations.AddField(
            model_name="courses",
            name="about_course_owner",
            field=models.TextField(blank=True, null=True),
        ),
    ]
