# Generated by Django 4.1.7 on 2023-06-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0054_remove_courses_about_course_owner_aboutcourseowner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutcourseowner",
            name="desc",
            field=models.TextField(blank=True, null=True),
        ),
    ]
