# Generated by Django 4.1.7 on 2023-06-19 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_profile_courses"),
        ("sms", "0055_alter_aboutcourseowner_desc"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="users.profile"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseEnrolled",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        related_name="enrolled_courses", to="sms.profilestudent"
                    ),
                ),
            ],
        ),
    ]
