# Generated by Django 4.1.7 on 2023-06-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0057_alter_topics_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topics", name="slug", field=models.SlugField(unique=True),
        ),
    ]
