# Generated by Django 4.1.7 on 2023-06-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0058_remove_topics_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="topics",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
