# Generated by Django 4.1.7 on 2023-06-19 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0059_topics_slug"),
    ]

    operations = [
        migrations.RemoveField(model_name="courses", name="prerequisites",),
    ]
