# Generated by Django 4.1.7 on 2023-06-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0060_remove_courses_prerequisites"),
    ]

    operations = [
        migrations.AddField(
            model_name="courses",
            name="prerequisites",
            field=models.ManyToManyField(blank=True, to="sms.courses"),
        ),
    ]
