# Generated by Django 4.1.7 on 2023-06-19 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0061_courses_prerequisites"),
    ]

    operations = [
        migrations.DeleteModel(name="CoursePrerequisites",),
    ]
