# Generated by Django 4.1.7 on 2023-06-19 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0062_delete_courseprerequisites"),
    ]

    operations = [
        migrations.RemoveField(model_name="courses", name="course_desc",),
        migrations.RemoveField(model_name="courses", name="desc_home",),
    ]
