# Generated by Django 4.1.7 on 2023-06-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0063_remove_courses_course_desc_remove_courses_desc_home"),
    ]

    operations = [
        migrations.AddField(
            model_name="topics",
            name="transcript",
            field=models.TextField(blank=True, null=True),
        ),
    ]
