# Generated by Django 4.1.7 on 2023-06-20 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0065_remove_topics_coursedesc"),
    ]

    operations = [
        migrations.RemoveField(model_name="topics", name="transcript",),
    ]
