# Generated by Django 4.1.7 on 2023-06-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0066_remove_topics_transcript"),
    ]

    operations = [
        migrations.AddField(
            model_name="topics",
            name="transcript",
            field=models.TextField(blank=True, null=True),
        ),
    ]
