# Generated by Django 4.1.7 on 2023-06-22 10:35

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0067_topics_transcript"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courses",
            name="desc",
            field=tinymce.models.HTMLField(blank=True, max_length=500, null=True),
        ),
    ]
