# Generated by Django 4.1.7 on 2023-06-22 10:39

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0068_alter_courses_desc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courses",
            name="desc",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
