# Generated by Django 4.1.7 on 2023-06-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0069_alter_courses_desc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courses", name="desc", field=models.TextField(null=True),
        ),
    ]
