# Generated by Django 4.1.7 on 2023-06-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0070_alter_courses_desc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whatyouwilllearn",
            name="desc",
            field=models.TextField(blank=True, max_length=900, null=True),
        ),
    ]
