# Generated by Django 4.1.7 on 2023-06-22 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0072_remove_courses_student_courses_students"),
    ]

    operations = [
        migrations.RenameField(
            model_name="courses", old_name="students", new_name="student",
        ),
    ]
