# Generated by Django 4.1.7 on 2023-06-22 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_profile_courses"),
        ("sms", "0074_remove_courses_student_courses_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courses",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="users.profile",
            ),
        ),
    ]
