# Generated by Django 4.1.7 on 2023-06-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_profile_courses"),
        ("sms", "0075_alter_courses_student"),
    ]

    operations = [
        migrations.RemoveField(model_name="courses", name="student",),
        migrations.AddField(
            model_name="courses",
            name="student",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="courses", to="users.profile"
            ),
        ),
    ]
