# Generated by Django 4.1.7 on 2023-06-24 09:58

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0076_remove_courses_student_courses_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topics",
            name="desc",
            field=tinymce.models.HTMLField(blank=True, max_length=500, null=True),
        ),
    ]
