# Generated by Django 4.1.7 on 2023-06-24 12:49

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0077_alter_topics_desc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topics",
            name="desc",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
