# Generated by Django 4.1 on 2023-12-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='partdesc2',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
