# Generated by Django 4.1 on 2022-12-25 15:57

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="option1",
            field=tinymce.models.HTMLField(max_length=200),
        ),
        migrations.AlterField(
            model_name="question",
            name="option2",
            field=tinymce.models.HTMLField(max_length=200),
        ),
        migrations.AlterField(
            model_name="question",
            name="option3",
            field=tinymce.models.HTMLField(max_length=200),
        ),
        migrations.AlterField(
            model_name="question",
            name="option4",
            field=tinymce.models.HTMLField(max_length=200),
        ),
    ]
