# Generated by Django 4.1.7 on 2023-04-15 16:34

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="img_partdesc1",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="img_partdesc2",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="partdesc1",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="partdesc2",
            field=models.CharField(blank=True, max_length=229, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="partdesc3",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
