# Generated by Django 3.1.4 on 2022-07-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
