# Generated by Django 4.1 on 2023-12-29 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_rename_course_name_course_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='courses',
            new_name='course_name',
        ),
    ]
