# Generated by Django 4.1.7 on 2023-05-31 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_alter_course_slug"),
    ]

    operations = [
        migrations.RemoveField(model_name="course", name="slug",),
    ]
