# Generated by Django 4.1.7 on 2023-05-22 17:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_course_img_partdesc1_course_img_partdesc2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="signature",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
