# Generated by Django 4.1 on 2023-12-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_course_partdesc2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
