# Generated by Django 4.1 on 2024-01-07 09:43

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_course_course_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('school_name', models.CharField(max_length=255)),
                ('logo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='school_logos/')),
                ('principal_signature', cloudinary.models.CloudinaryField(max_length=255, verbose_name='principal_signatures/')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.school'),
        ),
    ]
