# Generated by Django 4.1 on 2023-07-31 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0002_initial"),
        ("quiz", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="smscourses",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sms.courses",
            ),
        ),
    ]
