# Generated by Django 4.1.7 on 2023-05-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_course_signature"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="signby",
            field=models.CharField(blank=True, max_length=229, null=True),
        ),
    ]
