# Generated by Django 4.1 on 2024-01-07 09:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_school_course_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='school_logos'),
        ),
        migrations.AlterField(
            model_name='school',
            name='principal_signature',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='principal_signatures'),
        ),
    ]
