# Generated by Django 3.1.4 on 2022-07-29 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_course_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='number',
            new_name='pass_mark',
        ),
    ]
