# Generated by Django 4.1 on 2023-07-31 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0002_initial"),
        ("quiz", "0003_course_smscourses"),
    ]

    operations = [
        migrations.RemoveField(model_name="course", name="smscourses",),
        migrations.AlterField(
            model_name="course",
            name="course_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sms.courses",
            ),
        ),
    ]
