# Generated by Django 4.1.7 on 2023-05-22 17:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_course_signby"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="signature",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="signature"
            ),
        ),
    ]
