# Generated by Django 3.1.4 on 2022-07-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20220729_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='constant',
            field=models.PositiveIntegerField(default=2, null=True),
        ),
    ]
