# Generated by Django 4.1 on 2023-08-03 18:20

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_remove_course_smscourses_alter_course_course_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="option1",
            field=tinymce.models.HTMLField(max_length=200),
        ),
        migrations.AlterField(
            model_name="question",
            name="option2",
            field=tinymce.models.HTMLField(max_length=200),
        ),
        migrations.AlterField(
            model_name="question",
            name="option3",
            field=tinymce.models.HTMLField(max_length=200),
        ),
        migrations.AlterField(
            model_name="question",
            name="option4",
            field=tinymce.models.HTMLField(max_length=200),
        ),
        migrations.AlterField(
            model_name="question",
            name="question",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
