# Generated by Django 4.1.7 on 2023-05-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0005_alter_course_signature"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="signby_portfolio",
            field=models.CharField(blank=True, max_length=229, null=True),
        ),
    ]
