# Generated by Django 3.2.9 on 2022-01-21 14:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_course_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='img_quiz',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
