# Generated by Django 4.1 on 2024-01-07 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='admission_no',
        ),
    ]
