# Generated by Django 4.1 on 2023-08-03 22:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0006_alter_question_img_quiz_alter_question_option1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="img_quiz",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
