# Generated by Django 4.1.7 on 2023-05-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0006_course_signby_portfolio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="signby_portfolio",
            field=models.CharField(
                blank=True,
                default="Global Director, Codethinkers' Academy",
                max_length=229,
                null=True,
            ),
        ),
    ]
