# Generated by Django 4.1.7 on 2023-05-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0007_alter_course_signby_portfolio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="signby_portfolio",
            field=models.CharField(blank=True, max_length=229, null=True),
        ),
    ]
