# Generated by Django 4.1 on 2024-01-07 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ourse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.course'),
        ),
    ]
