# Generated by Django 4.1 on 2022-08-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0008_auto_20220731_1408"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="cert_note",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
