# Generated by Django 4.1 on 2024-01-07 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_student_ourse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='ourse',
            new_name='course',
        ),
    ]
