# Generated by Django 4.1 on 2023-08-09 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0006_alter_skillyouwillgain_title"),
        ("quiz", "0008_courseassessment_resultassessment_questionassessment"),
    ]

    operations = [
        migrations.RemoveField(model_name="courseassessment", name="img_partdesc1",),
        migrations.RemoveField(model_name="courseassessment", name="img_partdesc2",),
        migrations.RemoveField(model_name="courseassessment", name="partdesc1",),
        migrations.RemoveField(model_name="courseassessment", name="partdesc2",),
        migrations.RemoveField(model_name="courseassessment", name="partdesc3",),
        migrations.RemoveField(model_name="courseassessment", name="signature",),
        migrations.RemoveField(model_name="courseassessment", name="signby",),
        migrations.RemoveField(model_name="courseassessment", name="signby_portfolio",),
        migrations.AlterField(
            model_name="courseassessment",
            name="course_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sms.topics",
            ),
        ),
    ]
