# Generated by Django 4.1.7 on 2023-05-28 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0008_alter_course_signby_portfolio"),
    ]

    operations = [
        migrations.RemoveField(model_name="course", name="constant",),
    ]
