# Generated by Django 4.1 on 2022-08-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0009_course_cert_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="cert_note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
