# Generated by Django 4.1 on 2023-08-09 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0006_alter_skillyouwillgain_title"),
        ("quiz", "0009_remove_courseassessment_img_partdesc1_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CourseAssessment", new_name="TopicsAssessment",
        ),
    ]
