# Generated by Django 4.1 on 2023-08-10 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0006_alter_skillyouwillgain_title"),
        ("quiz", "0010_rename_courseassessment_topicsassessment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topicsassessment",
            name="course_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sms.courses",
            ),
        ),
    ]
