# Generated by Django 4.1 on 2022-08-12 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0010_alter_course_cert_note"),
    ]

    operations = [
        migrations.RemoveField(model_name="course", name="cert_note",),
    ]
