# Generated by Django 4.1 on 2022-08-12 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0012_certificate_note"),
    ]

    operations = [
        migrations.RemoveField(model_name="certificate_note", name="desc",),
    ]
