# Generated by Django 4.1 on 2024-01-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='portfolio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
