# Generated by Django 4.1 on 2022-08-29 12:23

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0014_course_created_course_updated_question_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
