# Generated by Django 4.1 on 2024-01-12 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_school_portfolio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
