# Generated by Django 4.1 on 2024-01-13 01:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='school_logos'),
        ),
        migrations.AlterField(
            model_name='school',
            name='principal_signature',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='principal_signatures'),
        ),
    ]
