# Generated by Django 4.1 on 2023-10-13 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_alter_course_cert_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='cert_price',
        ),
    ]
