# Generated by Django 4.1 on 2024-02-10 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_alter_course_manyschools'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='school',
        ),
    ]
