# Generated by Django 4.1 on 2024-02-10 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_remove_course_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='manyschools',
            new_name='schools',
        ),
    ]
