# Generated by Django 4.1 on 2024-02-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_remove_course_schools'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
