# Generated by Django 4.1 on 2024-03-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_course_duration_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
