# Generated by Django 4.1 on 2024-03-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_alter_course_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultassessment',
            name='option',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
