# Generated by Django 5.0.4 on 2024-08-15 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_resultassessment_option'),
    ]

    operations = [
    ]
