# Generated by Django 5.0.4 on 2025-08-14 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0026_update_verification_codes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['course_name__title']},
        ),
        migrations.AlterModelOptions(
            name='topicsassessment',
            options={'ordering': ['course_name__title']},
        ),
    ]
