# Generated by Django 5.0.4 on 2025-08-18 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0033_remove_result_exam_type_remove_result_session_and_more'),
        ('sms', '0005_alter_topics_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['course_name__title'], 'verbose_name': 'Exam', 'verbose_name_plural': 'Exams'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='img_partdesc1',
        ),
        migrations.RemoveField(
            model_name='course',
            name='img_partdesc2',
        ),
        migrations.RemoveField(
            model_name='course',
            name='partdesc1',
        ),
        migrations.RemoveField(
            model_name='course',
            name='partdesc2',
        ),
        migrations.RemoveField(
            model_name='course',
            name='partdesc3',
        ),
        migrations.RemoveField(
            model_name='course',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='course',
            name='signby',
        ),
        migrations.RemoveField(
            model_name='course',
            name='signby_portfolio',
        ),
        migrations.AddField(
            model_name='course',
            name='course_pay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='exam_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.examtype'),
        ),
        migrations.AddField(
            model_name='course',
            name='full_screen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='num_attemps',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='course',
            name='room_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='schools',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='quiz.school'),
        ),
        migrations.AddField(
            model_name='course',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.session'),
        ),
        migrations.AddField(
            model_name='course',
            name='show_questions',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='course',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.term'),
        ),
        migrations.AddField(
            model_name='result',
            name='exam_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.examtype'),
        ),
        migrations.AddField(
            model_name='result',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.session'),
        ),
        migrations.AddField(
            model_name='result',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.term'),
        ),
        migrations.AlterField(
            model_name='course',
            name='question_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['schools'], name='quiz_course_schools_5b5dd4_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_name'], name='quiz_course_course__73d637_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['session'], name='quiz_course_session_3d470c_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['term'], name='quiz_course_term_id_a35bdf_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['exam_type'], name='quiz_course_exam_ty_c44a14_idx'),
        ),
    ]
