# Generated by Django 5.0.4 on 2025-08-18 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0038_alter_course_options_remove_course_img_partdesc1_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='course',
            name='quiz_course_session_3d470c_idx',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='quiz_course_term_id_a35bdf_idx',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='quiz_course_exam_ty_c44a14_idx',
        ),
        migrations.RemoveField(
            model_name='course',
            name='exam_type',
        ),
        migrations.RemoveField(
            model_name='course',
            name='session',
        ),
        migrations.RemoveField(
            model_name='course',
            name='term',
        ),
    ]
