# Generated by Django 5.0.4 on 2025-08-18 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0039_remove_course_quiz_course_session_3d470c_idx_and_more'),
        ('sms', '0005_alter_topics_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='exam_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.examtype'),
        ),
        migrations.AddField(
            model_name='course',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.session'),
        ),
        migrations.AddField(
            model_name='course',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.term'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['session'], name='quiz_course_session_3d470c_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['term'], name='quiz_course_term_id_a35bdf_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['exam_type'], name='quiz_course_exam_ty_c44a14_idx'),
        ),
    ]
