# Generated by Django 5.0.4 on 2025-08-19 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0040_course_exam_type_course_session_course_term_and_more'),
        ('sms', '0005_alter_topics_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='categories',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='sms.categories'),
        ),
    ]
