# Generated by Django 5.0.4 on 2025-07-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webprojects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='external_css_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
