# Generated by Django 5.0.4 on 2026-02-13 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0008_alter_topics_categories_alter_topics_courses'),
        ('webprojects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.topics'),
        ),
    ]
