# Generated by Django 5.0.4 on 2025-07-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webprojects', '0002_project_external_css_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='python_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
