# Generated by Django 5.0.4 on 2026-02-20 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0010_alter_topics_options'),
        ('webprojects', '0003_file_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='current_topic',
            field=models.ForeignKey(blank=True, help_text='Which lesson is this file for?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_files', to='sms.topics'),
        ),
    ]
