# Generated by Django 5.0.4 on 2026-02-20 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0041_course_categories'),
        ('sms', '0010_alter_topics_options'),
        ('webprojects', '0004_file_current_topic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_topics', models.ManyToManyField(blank=True, related_name='completed_by_students', to='sms.topics')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.course')),
                ('current_topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.topics')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
    ]
