# Generated by Django 5.0.4 on 2026-02-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webprojects', '0004_rename_title_project_name_remove_project_css_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
