# Generated by Django 5.0.4 on 2025-07-11 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webprojects', '0004_rename_title_project_name_remove_project_css_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='webprojects.folder'),
        ),
    ]
