# Generated by Django 5.0.4 on 2026-02-20 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0041_course_categories'),
        ('sms', '0010_alter_topics_options'),
        ('webprojects', '0005_studentprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprogress',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.course'),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='current_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.topics'),
        ),
    ]
