# Generated by Django 5.0.4 on 2026-02-09 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webprojects', '0005_alter_file_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['name']},
        ),
    ]
