# Generated by Django 5.0.4 on 2025-07-13 13:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webprojects', '0006_alter_file_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
