# Generated by Django 5.0.4 on 2026-02-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webprojects', '0006_alter_studentprogress_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprogress',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
