# Generated by Django 5.0.4 on 2026-02-21 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0010_alter_topics_options'),
        ('webprojects', '0007_studentprogress_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprogress',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.courses'),
        ),
    ]
