# Generated by Django 5.0.4 on 2025-08-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webprojects', '0007_file_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='excel',
            field=models.FileField(blank=True, null=True, upload_to='excels/'),
        ),
    ]
