# Generated by Django 5.0.4 on 2025-08-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webprojects', '0008_file_excel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='excel',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
