# Generated by Django 5.0.4 on 2025-08-27 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webprojects', '0009_remove_file_excel_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
