# Generated by Django 5.0.4 on 2026-07-08 12:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0014_alter_categories_desc_alter_categories_name_and_more'),
        ('webprojects', '0010_leaderboardentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('first_to_finish', '🥇 First to Finish'), ('fast_learner', '⚡ Fast Learner'), ('perfect_score', '🎯 Perfect Score'), ('code_master', '💻 Code Master'), ('ai_champion', '🧠 AI Champion'), ('consistent', '🔥 Consistent Learner')], max_length=50, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=10)),
                ('xp_reward', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
            },
        ),
        migrations.CreateModel(
            name='LearningStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Learning Streak',
                'verbose_name_plural': 'Learning Streaks',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StudentBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Student Badge',
                'verbose_name_plural': 'Student Badges',
                'ordering': ['-earned_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='leaderboardentry',
            options={'ordering': ['rank'], 'verbose_name': 'Leaderboard Entry', 'verbose_name_plural': 'Leaderboard Entries'},
        ),
        migrations.AlterModelOptions(
            name='studentprogress',
            options={'ordering': ['-last_updated'], 'verbose_name': 'Student Progress', 'verbose_name_plural': 'Student Progress'},
        ),
        migrations.AlterModelOptions(
            name='studentxp',
            options={'verbose_name': 'Student XP', 'verbose_name_plural': 'Student XP'},
        ),
        migrations.RemoveField(
            model_name='leaderboardentry',
            name='completed_topics',
        ),
        migrations.RemoveField(
            model_name='leaderboardentry',
            name='completion_percentage',
        ),
        migrations.RemoveField(
            model_name='leaderboardentry',
            name='points',
        ),
        migrations.RemoveField(
            model_name='leaderboardentry',
            name='total_topics',
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='average_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='champion_xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='coding_challenges_passed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='completion_time_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='incorrect_code_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='learning_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='modules_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='total_modules',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='assessment_scores',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='coding_challenges_passed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='course_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='current_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='first_attempt_topics',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='first_to_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='incorrect_code_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='last_activity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='longest_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='total_assessments_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaderboardentry',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard', to='sms.courses'),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='sms.courses'),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='current_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_students', to='sms.topics'),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentxp',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xp_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='leaderboardentry',
            index=models.Index(fields=['course', 'rank'], name='webprojects_course__4963b9_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboardentry',
            index=models.Index(fields=['course', '-champion_xp'], name='webprojects_course__7f0295_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprogress',
            index=models.Index(fields=['student', 'course'], name='webprojects_student_a49d5d_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprogress',
            index=models.Index(fields=['course', '-current_streak'], name='webprojects_course__722798_idx'),
        ),
        migrations.AddField(
            model_name='learningstreak',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_streaks', to='sms.courses'),
        ),
        migrations.AddField(
            model_name='learningstreak',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_streaks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentbadge',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_to', to='webprojects.badge'),
        ),
        migrations.AddField(
            model_name='studentbadge',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badges_awarded', to='sms.courses'),
        ),
        migrations.AddField(
            model_name='studentbadge',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='learningstreak',
            index=models.Index(fields=['student', 'course', '-date'], name='webprojects_student_000b8f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='learningstreak',
            unique_together={('student', 'course', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='studentbadge',
            unique_together={('student', 'badge', 'course')},
        ),
    ]
