# Generated by Django 5.0.4 on 2026-07-09 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0014_alter_categories_desc_alter_categories_name_and_more'),
        ('webprojects', '0011_badge_learningstreak_studentbadge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprogress',
            name='module_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='total_time_spent_seconds',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='sms.courses'),
        ),
    ]
