# Generated by Django 5.0.4 on 2026-07-15 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0014_alter_categories_desc_alter_categories_name_and_more'),
        ('webprojects', '0012_studentprogress_module_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='sms.courses'),
            preserve_default=False,
        ),
    ]
