# Generated by Django 5.0.4 on 2026-02-09 14:26

import django.db.models.deletion
import webprojects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0007_courses_is_programming'),
        ('webprojects', '0012_alter_file_topic_alter_folder_topic_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={},
        ),
        migrations.AlterField(
            model_name='file',
            name='topic',
            field=models.ForeignKey(blank=True, default=webprojects.models.get_general_topic, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.topics'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='topic',
            field=models.ForeignKey(blank=True, default=webprojects.models.get_general_topic, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.topics'),
        ),
        migrations.AlterField(
            model_name='project',
            name='topic',
            field=models.ForeignKey(blank=True, default=webprojects.models.get_general_topic, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.topics'),
        ),
    ]
