# Generated by Django 5.0.4 on 2026-02-09 14:06

import django.db.models.deletion
from django.db import migrations, models


def create_general_topic(apps, schema_editor):
    Topics = apps.get_model('sms', 'Topics')
    Categories = apps.get_model('sms', 'Categories')

    # Ensure there is a "General" category
    general_category, _ = Categories.objects.get_or_create(name='General')

    # Ensure there is a "General" topic with that category
    general_topic, _ = Topics.objects.get_or_create(
        title='General',
        defaults={'categories_id': general_category.id}
    )
    return general_topic


def assign_default_topic(apps, schema_editor):
    Project = apps.get_model('webprojects', 'Project')
    Folder = apps.get_model('webprojects', 'Folder')
    File = apps.get_model('webprojects', 'File')
    Topics = apps.get_model('sms', 'Topics')

    general_topic = Topics.objects.filter(title='General').first()
    if general_topic is None:
        general_topic = create_general_topic(apps, schema_editor)

    # Assign default topic to existing records
    Project.objects.filter(topic__isnull=True).update(topic=general_topic)
    Folder.objects.filter(topic__isnull=True).update(topic=general_topic)
    File.objects.filter(topic__isnull=True).update(topic=general_topic)


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0007_courses_is_programming'),
        ('webprojects', '0010_alter_file_topic'),
    ]

    operations = [
        # Add topic fields
        migrations.AddField(
            model_name='folder',
            name='topic',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='sms.topics',
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='topic',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='sms.topics',
            ),
        ),
        migrations.AlterField(
            model_name='file',
            name='topic',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='sms.topics',
            ),
        ),

        # Assign default topic to existing records
        migrations.RunPython(assign_default_topic),
    ]
