# Generated by Django 5.0.4 on 2026-07-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webprojects', '0013_project_assigned_port_alter_studentprogress_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='admin_password',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
