# Generated by Django 5.0.4 on 2026-07-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webprojects', '0014_project_admin_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='subdomain',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
