# Generated by Django 5.0.4 on 2026-02-09 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0007_courses_is_programming'),
        ('webprojects', '0014_populate_default_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='file',
            name='topic',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.topics'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='topic',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.topics'),
        ),
        migrations.AlterField(
            model_name='project',
            name='topic',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.topics'),
        ),
    ]
