# Generated by Django 5.0.4 on 2026-02-09 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webprojects', '0013_alter_file_options_alter_file_topic_and_more'),
        ('webprojects', '0015_alter_file_options_alter_file_topic_and_more'),
    ]

    operations = [
    ]
