# Generated by Django 5.0.4 on 2026-07-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webprojects', '0015_project_subdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
