# Generated by Django 5.0.4 on 2026-07-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webprojects', '0016_project_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending Payment'), ('suspended', 'Suspended')], default='active', max_length=20),
        ),
    ]
