# Generated by Django 5.0.4 on 2026-02-09 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0007_courses_is_programming'),
        ('webprojects', '0017_alter_file_options_alter_file_topic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='topic',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.topics'),
        ),
    ]
