# Generated by Django 5.0.4 on 2026-07-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webprojects', '0017_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_amount', models.DecimalField(decimal_places=2, default=15000.0, max_digits=10)),
                ('subscription_currency', models.CharField(default='NGN', max_length=3)),
                ('bank_name', models.CharField(default='GTBank', max_length=100)),
                ('account_number', models.CharField(default='0123456789', max_length=20)),
                ('account_name', models.CharField(default='Codethinkers Academy', max_length=200)),
                ('payment_instructions', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
