# Generated by Django 5.0.4 on 2026-07-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webprojects', '0018_platformsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ai_model',
            field=models.CharField(default='gpt-4o-mini', max_length=50),
        ),
    ]
