# Generated by Django 5.0.4 on 2026-08-01 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webprojects', '0019_project_ai_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_type', models.CharField(choices=[('scaffold', 'Scaffold (new project)'), ('incremental', 'Incremental (existing project)')], max_length=20)),
                ('prompt', models.TextField(blank=True)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('success_after_autofix', 'Success (after deterministic auto-fix)'), ('success_after_ai_retry', 'Success (after AI retry)'), ('failure_validation', 'Failed — static validation'), ('failure_smoke_test', 'Failed — smoke test (runtime error)'), ('failure_exception', 'Failed — unhandled exception'), ('failure_max_retries', 'Failed — exhausted retries')], max_length=30)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('smoke_test_errors', models.JSONField(blank=True, default=list)),
                ('fix_patterns_triggered', models.JSONField(blank=True, default=list)),
                ('rule_files_loaded', models.JSONField(blank=True, default=list)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='build_attempts', to='webprojects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['build_type', 'outcome'], name='webprojects_build_t_e50f39_idx'), models.Index(fields=['-created_at'], name='webprojects_created_e44e58_idx')],
            },
        ),
    ]
