# Generated by Django 5.0.4 on 2026-02-09 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webprojects', '0018_alter_file_topic'),
        ('webprojects', '0019_add_file_topic'),
    ]

    operations = [
    ]
