# Generated by Django 5.0.4 on 2026-02-10 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webprojects', '0020_merge_0018_alter_file_topic_0019_add_file_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='webprojects.project'),
        ),
    ]
