# Generated by Django 5.0.4 on 2026-02-11 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webprojects', '0002_rename_title_project_name_remove_project_css_code_and_more'),
        ('webprojects', '0021_alter_file_project'),
    ]

    operations = [
    ]
