# Generated by Django 5.0.4 on 2026-01-14 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
        ('student', '0020_alter_certificate_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorearning',
            name='student',
        ),
        migrations.AddField(
            model_name='instructorearning',
            name='certificate_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.certificatepayment'),
        ),
        migrations.AddField(
            model_name='instructorearning',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.payment'),
        ),
        migrations.AlterField(
            model_name='instructorearning',
            name='amount_paid',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='instructorearning',
            name='instructor_amount',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='instructorearning',
            name='platform_amount',
            field=models.PositiveBigIntegerField(),
        ),
    ]
