# Generated by Django 5.0.4 on 2025-09-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_fastapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programpage',
            name='benefits',
            field=models.TextField(),
        ),
    ]
