# Generated by Django 5.0.4 on 2025-09-17 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_fastapi', '0002_alter_programpage_benefits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programpage',
            name='cta_text',
        ),
        migrations.RemoveField(
            model_name='programpage',
            name='subtitle',
        ),
    ]
