# Generated by Django 4.1.7 on 2023-06-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveBigIntegerField()),
                ("ref", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("verifeied", models.BooleanField(default=False)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ("-date_created",),},
        ),
    ]
