# Generated by Django 4.1 on 2023-12-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatepayment',
            name='f_code',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
