# Generated by Django 4.1 on 2023-12-27 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='f_code',
            new_name='referral_code',
        ),
    ]
