# Generated by Django 4.1 on 2023-12-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
