# Generated by Django 4.1 on 2023-07-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_course",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
