# Generated by Django 4.1.7 on 2023-05-31 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("student", "0002_certificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="code",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="holder",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="issued_date",
            field=models.DateField(null=True),
        ),
    ]
