# Generated by Django 4.1 on 2023-07-26 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment", old_name="user", new_name="user_name",
        ),
    ]
