# Generated by Django 4.1.7 on 2023-07-20 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_cart_order_payment_orderitem_order_courses_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="payment", name="payment_course",),
    ]
