# Generated by Django 4.1 on 2023-07-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0002_initial"),
        ("student", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="payment", name="courses",),
        migrations.AddField(
            model_name="payment",
            name="courses",
            field=models.ManyToManyField(
                null=True, related_name="payments", to="sms.courses"
            ),
        ),
    ]
