# Generated by Django 4.1 on 2023-12-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        ('student', '0002_rename_f_code_payment_referral_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='referral_code',
        ),
        migrations.AlterField(
            model_name='certificatepayment',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='certificates', to='quiz.course'),
        ),
    ]
