# Generated by Django 4.1 on 2023-12-02 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0002_referrermentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrermentor',
            name='learner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referrermentor',
            name='referred_students',
            field=models.ManyToManyField(blank=True, related_name='referrer_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referrermentor',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
