# Generated by Django 4.1.7 on 2023-06-30 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_payment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment", old_name="verifeied", new_name="verified",
        ),
    ]
