# Generated by Django 4.1 on 2023-07-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PDFDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("pdf_file", models.FileField(upload_to="pdf_documents/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
