# Generated by Django 4.1 on 2022-08-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0003_signature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logo",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="signature",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
