# Generated by Django 4.1 on 2023-07-31 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0003_pdfdocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdfdocument",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                default="500",
                max_digits=10,
                max_length=225,
                null=True,
            ),
        ),
    ]
