# Generated by Django 4.1 on 2024-01-12 23:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_advertisementimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementimage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='advertisement_images'),
        ),
    ]
