# Generated by Django 4.1 on 2023-12-13 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_initial'),
        ('student', '0003_alter_certificatepayment_f_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrermentor',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='referrercourses', to='sms.courses'),
        ),
    ]
