# Generated by Django 4.1 on 2023-07-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0002_initial"),
        ("student", "0003_remove_payment_courses_payment_courses"),
    ]

    operations = [
        migrations.RemoveField(model_name="payment", name="user",),
        migrations.AddField(
            model_name="payment",
            name="payment_user",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="courses",
            field=models.ManyToManyField(related_name="payments", to="sms.courses"),
        ),
    ]
