# Generated by Django 4.1 on 2023-07-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0003_rename_payment_paymentn"),
    ]

    operations = [
        migrations.RemoveField(model_name="paymentn", name="payment_course",),
        migrations.AlterField(
            model_name="paymentn",
            name="courses",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
