# Generated by Django 4.1 on 2023-12-02 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_referrermentor_learner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referrermentor',
            name='learner',
        ),
    ]
