# Generated by Django 4.1.7 on 2023-07-20 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0002_frequentlyaskquestions_partners_and_more"),
        ("student", "0003_remove_payment_payment_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="courses",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="sms.courses",
            ),
        ),
    ]
