# Generated by Django 4.1.7 on 2023-04-13 13:45

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0003_partlogo"),
    ]

    operations = [
        migrations.AddField(
            model_name="logo",
            name="partdesc1",
            field=tinymce.models.HTMLField(default=""),
        ),
        migrations.AddField(
            model_name="logo",
            name="partdesc2",
            field=tinymce.models.HTMLField(default=""),
        ),
        migrations.AddField(
            model_name="logo",
            name="partdesc3",
            field=tinymce.models.HTMLField(default=""),
        ),
    ]
