# Generated by Django 4.1.7 on 2023-07-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0003_rename_verifeied_payment_verified"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment", options={"ordering": ["-created"]},
        ),
        migrations.RenameField(
            model_name="payment", old_name="verified", new_name="paid",
        ),
        migrations.RemoveField(model_name="payment", name="date_created",),
        migrations.RemoveField(model_name="payment", name="ref",),
        migrations.AddField(
            model_name="payment",
            name="city",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="first_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="last_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="paystack_ref",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="payment",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
