# Generated by Django 4.1.7 on 2023-07-01 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0004_alter_payment_options_rename_verified_payment_paid_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment", options={"ordering": ("-date_created",)},
        ),
        migrations.RemoveField(model_name="payment", name="city",),
        migrations.RemoveField(model_name="payment", name="created",),
        migrations.RemoveField(model_name="payment", name="first_name",),
        migrations.RemoveField(model_name="payment", name="last_name",),
        migrations.RemoveField(model_name="payment", name="paid",),
        migrations.RemoveField(model_name="payment", name="paystack_ref",),
        migrations.RemoveField(model_name="payment", name="updated",),
        migrations.AddField(
            model_name="payment",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="ref",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="verified",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
