# Generated by Django 4.1.7 on 2023-05-31 16:38

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0004_alter_certificate_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="code",
            field=models.CharField(
                default=student.models.generate_certificate_code,
                max_length=10,
                unique=True,
            ),
        ),
    ]
