# Generated by Django 4.1 on 2023-07-25 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0002_initial"),
        ("student", "0004_remove_payment_user_payment_payment_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="payment", name="courses",),
        migrations.AddField(
            model_name="payment",
            name="courses",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="sms.courses",
            ),
        ),
    ]
