# Generated by Django 4.1 on 2023-12-14 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_referrermentor_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrermentor',
            name='cert_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cert_payment', to='student.certificatepayment'),
        ),
    ]
