# Generated by Django 4.1 on 2023-07-23 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0001_initial"),
        ("student", "0004_remove_paymentn_payment_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentn",
            name="courses",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="sms.courses",
            ),
        ),
    ]
