# Generated by Django 4.1 on 2024-01-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_advertisementimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementimage',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
