# Generated by Django 4.1.7 on 2023-04-14 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0004_logo_partdesc1_logo_partdesc2_logo_partdesc3"),
    ]

    operations = [
        migrations.RemoveField(model_name="logo", name="partdesc1",),
        migrations.RemoveField(model_name="logo", name="partdesc2",),
        migrations.RemoveField(model_name="logo", name="partdesc3",),
    ]
