# Generated by Django 4.1 on 2023-07-31 13:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0004_pdfdocument_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdfdocument",
            name="img_ebook",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="Ebook images"
            ),
        ),
    ]
