# Generated by Django 4.1 on 2023-07-23 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0001_initial"),
        ("users", "0002_profile_status_type"),
        ("student", "0005_alter_paymentn_courses"),
    ]

    operations = [
        migrations.RenameModel(old_name="PaymentN", new_name="Payment",),
    ]
