# Generated by Django 4.1.7 on 2023-07-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0005_alter_payment_options_remove_payment_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
