# Generated by Django 4.1 on 2023-07-31 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0005_pdfdocument_img_ebook"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pdfdocument", old_name="created_at", new_name="created",
        ),
        migrations.RenameField(
            model_name="pdfdocument", old_name="description", new_name="desc",
        ),
    ]
