# Generated by Django 4.1 on 2024-01-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_advertisementimage_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrermentor',
            name='withdrawal_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='referrermentor',
            name='withdrawal_request_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referrermentor',
            name='withdrawal_request_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Rejected')], default='pending', max_length=20),
        ),
    ]
