# Generated by Django 4.1 on 2023-07-31 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("student", "0006_rename_created_at_pdfdocument_created_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveBigIntegerField(null=True)),
                ("ref", models.CharField(max_length=250, null=True)),
                ("first_name", models.CharField(max_length=250, null=True)),
                ("last_name", models.CharField(max_length=200, null=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("verified", models.BooleanField(default=False)),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "payment_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.profile",
                    ),
                ),
                (
                    "pdfdocument",
                    models.ManyToManyField(
                        related_name="docpayments", to="student.pdfdocument"
                    ),
                ),
            ],
        ),
    ]
