# Generated by Django 4.1.7 on 2023-07-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0006_alter_payment_date_created_alter_payment_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="ref",
            field=models.CharField(default="839jdei83j", max_length=200, null=True),
        ),
    ]
