# Generated by Django 4.1 on 2023-12-14 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_remove_referrermentor_cert_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referrermentor',
            name='referred_count',
        ),
        migrations.AddField(
            model_name='referrermentor',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
