# Generated by Django 4.1 on 2023-08-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0007_docpayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdfdocument",
            name="pdf_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
