# Generated by Django 4.1 on 2023-12-14 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_remove_referrermentor_referred_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrermentor',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='referrermentor',
            name='bank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='referrermentor',
            name='phone_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
