# Generated by Django 4.1 on 2024-01-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_withdrawalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrermentor',
            name='paystack_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
