# Generated by Django 4.1.7 on 2023-07-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0007_alter_payment_ref"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="ref",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
