# Generated by Django 4.1 on 2023-12-20 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0008_referrermentor_account_number_referrermentor_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatepayment',
            name='user_association',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
