# Generated by Django 4.1 on 2024-01-18 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_referrermentor_paystack_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referrermentor',
            name='paystack_customer_id',
        ),
        migrations.RemoveField(
            model_name='referrermentor',
            name='withdrawal_balance',
        ),
        migrations.RemoveField(
            model_name='referrermentor',
            name='withdrawal_request_date',
        ),
        migrations.RemoveField(
            model_name='referrermentor',
            name='withdrawal_request_status',
        ),
        migrations.DeleteModel(
            name='WithdrawalRequest',
        ),
    ]
