# Generated by Django 4.1.7 on 2023-07-07 09:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_profile_courses"),
        ("student", "0008_alter_payment_ref"),
    ]

    operations = [
        migrations.AlterModelOptions(name="payment", options={},),
        migrations.AddField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.profile",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="payment", name="email", field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="payment",
            name="verified",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.CreateModel(
            name="UserWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(default="NGN", max_length=50, null=True)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.profile",
                    ),
                ),
            ],
        ),
    ]
