# Generated by Django 5.0.4 on 2024-07-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_remove_referrermentor_paystack_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrermentor',
            name='referer_per',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
