# Generated by Django 4.1.7 on 2023-07-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0009_alter_payment_options_payment_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment", name="ref", field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="payment",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
