# Generated by Django 4.1 on 2023-12-21 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_certificatepayment_user_association'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatepayment',
            name='user_association',
        ),
    ]
