# Generated by Django 4.1 on 2023-10-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_question_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='content_type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
