# Generated by Django 5.0.4 on 2024-07-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_referrermentor_referer_per'),
    ]

    operations = [
        migrations.CreateModel(
            name='PercentageReferrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referer_per', models.CharField(blank=True, default='20', max_length=20, null=True)),
            ],
        ),
    ]
