# Generated by Django 4.1 on 2023-12-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_initial'),
        ('student', '0010_remove_certificatepayment_user_association'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebookspayment',
            name='courses',
            field=models.ManyToManyField(related_name='ebooks', to='sms.courses'),
        ),
    ]
