# Generated by Django 4.1 on 2023-10-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0006_alter_skillyouwillgain_title'),
        ('student', '0010_payment_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docpayment',
            name='pdfdocument',
        ),
        migrations.AddField(
            model_name='docpayment',
            name='content_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='docpayment',
            name='courses',
            field=models.ManyToManyField(related_name='certificates', to='sms.courses'),
        ),
    ]
