# Generated by Django 4.1.7 on 2023-07-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0010_alter_payment_ref_alter_payment_verified"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment", options={"ordering": ("-date_created",)},
        ),
        migrations.RemoveField(model_name="payment", name="user",),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="ref",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
