# Generated by Django 5.0.4 on 2024-07-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_percentagereferrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='f_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
