# Generated by Django 4.1 on 2023-12-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_ebookspayment_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebookspayment',
            name='courses',
            field=models.ManyToManyField(related_name='ebooks', to='student.pdfdocument'),
        ),
    ]
