# Generated by Django 5.0.4 on 2024-07-17 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_payment_f_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_user',
        ),
    ]
