# Generated by Django 5.0.4 on 2024-07-18 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_remove_payment_payment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referrermentor',
            name='referer_per',
        ),
    ]
