# Generated by Django 4.1 on 2023-10-07 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_ebookspayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebookspayment',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='pdfdocument',
            name='pdf_file',
        ),
    ]
