# Generated by Django 5.0.4 on 2024-08-15 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_remove_referrermentor_referer_per'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='code',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='holder',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='issued_date',
        ),
    ]
