# Generated by Django 4.1 on 2023-12-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_payment_f_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatepayment',
            name='f_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='f_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
