# Generated by Django 4.1 on 2023-12-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        ('student', '0016_alter_certificatepayment_f_code_alter_payment_f_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatepayment',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='certificates', to='quiz.course'),
        ),
    ]
