# Generated by Django 4.1 on 2023-11-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_remove_course_cert_price'),
        ('student', '0016_alter_certificatepayment_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatepayment',
            name='courses',
            field=models.ManyToManyField(related_name='certificates', to='quiz.course'),
        ),
    ]
