# Generated by Django 4.1 on 2023-12-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_initial'),
        ('student', '0017_alter_certificatepayment_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='payments', to='sms.courses'),
        ),
    ]
