# Generated by Django 5.0.4 on 2024-08-15 15:40

from django.db import migrations

from student.models import generate_certificate_code

from django.db import migrations
from student.models import generate_certificate_code  # Import your function

def update_verification_codes(apps, schema_editor):
    Certificate = apps.get_model('student', 'Certificate')
    for certificate in Certificate.objects.all():
        certificate.code = generate_certificate_code()
        certificate.save()

class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_certificate_code_alter_certificate_user'),  # Ensure this migration exists
    ]

    operations = [
        migrations.RunPython(update_verification_codes),
    ]


# class Migration(migrations.Migration):

#     dependencies = [
#         ('student', '0018_certificate_code_alter_certificate_user'),
#     ]

#     operations = [
#     ]
