# Generated by Django 4.1 on 2023-12-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_certificatepayment_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatepayment',
            name='referral_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
