# Generated by Django 4.1 on 2023-12-02 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_alter_certificatepayment_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatepayment',
            name='referral_code',
        ),
    ]
