# Generated by Django 5.0.4 on 2025-08-14 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCertificateCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='certificatedownload',
            name='certificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='certificate_stats.coursecertificatecount'),
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
